apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-fast
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  zone: eu-west-1a
  iopsPerGB: "10"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-slow
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: eu-west-1a
reclaimPolicy: Retain
mountOptions:
  - debug